FROM r1tschy/sailfishos-platform-sdk-tooling
LABEL Author="Richard Liebscher <r1tschy@yahoo.de>"

ARG TARGET_VERSION

COPY target/target-armv7hl.tar.gz .

RUN set -ex &&\
 sudo zypper ref &&\
 sdk-assistant -y create SailfishOS-$TARGET_VERSION-armv7hl target-armv7hl.tar.gz &&\
 sudo rm -rf /srv/mer/targets/SailfishOS-$TARGET_VERSION-armv7hl/var/cache/zypp &&\
 sudo rm -rf /var/cache/zypp target-*.tar.gz