FROM r1tschy/sailfishos-platform-sdk-base AS builder
LABEL Author="Richard Liebscher <r1tschy@yahoo.de>"

ARG TARGET_VERSION

USER nemo
WORKDIR /home/nemo

COPY target/tooling-i486.tar.gz .

RUN set -ex &&\
 sudo mkdir /host_targets &&\
 sudo zypper ref &&\
 sdk-assistant -y create SailfishOS-$TARGET_VERSION tooling-i486.tar.gz &&\
 sudo rm -rf /srv/mer/toolings/SailfishOS-$TARGET_VERSION/var/cache/zypp/*


FROM r1tschy/sailfishos-platform-sdk-base
LABEL Author="Richard Liebscher <r1tschy@yahoo.de>"

ARG TARGET_VERSION

USER nemo
WORKDIR /home/nemo

COPY --from=builder /etc/machine-id /etc/machine-id
COPY --from=builder /srv/mer/toolings/SailfishOS-$TARGET_VERSION /srv/mer/toolings/SailfishOS-$TARGET_VERSION

