FROM r1tschy/sailfishos-platform-sdk-tooling AS builder
LABEL Author="Richard Liebscher <r1tschy@yahoo.de>"

ARG TARGET_VERSION

COPY target/target-i486.tar.gz .

RUN set -ex &&\
 sudo zypper ref &&\
 sdk-assistant -y create SailfishOS-$TARGET_VERSION-i486 target-i486.tar.gz &&\
 sudo rm -rf /srv/mer/targets/SailfishOS-$TARGET_VERSION-i486/var/cache/zypp/*


FROM r1tschy/sailfishos-platform-sdk-tooling
LABEL Author="Richard Liebscher <r1tschy@yahoo.de>"

ARG TARGET_VERSION

COPY --from=builder /srv/mer/targets/SailfishOS-$TARGET_VERSION-i486 /srv/mer/targets/SailfishOS-$TARGET_VERSION-i486
