name: Build Docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: ./build.sh
      
      - name: Test images
        run: ./test.sh

      - name: Docker Hub login
        run: echo "${{ secrets.DH_PAT }}" | docker login --username "${{ secrets.DH_USER }}" --password-stdin

      - name: GHCR login
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Push images
        run: ./push.sh          